### PR TITLE
Fix CGO_ENABLED for AmazonLinux2 drivers by detecting architecture type

### LINKED ISSUE #158: 0.9.0 release fails to build AmazonLinux2 drivers
**Description of Bug**

We tested out 0.9.0 today and noticed a new issue with AmazonLinux2 kernel drivers (specifically for libs version `3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4`). Here's some output from our automation that utilizes driverkit:
```
[ 2022-06-15 16:31:55,897 ] INFO - driverkit.py:137 - Does not exist in bucket! Building: [ scwx_amzn_5.4.68-34.125.amzn2.x86_64_1.ko ]
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
```

It seems the x86_64 binary is built with `CGO_ENABLED=0`.

**Steps to Reproduce**

Can be reproduced with the following using the `amd64` release from the releases page:

1. Download 0.9.0 release from release page: https://github.com/falcosecurity/driverkit/releases/download/v0.9.0/driverkit_0.9.0_linux_amd64.tar.gz
2. Un-tar to `$(pwd)`
3. Spin up linux container (if not on linux):
```
docker run -it -v $(pwd):/test ubuntu:latest
```
4. Run a build for Amazon Linux 2 (with libs version `3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4`):
```
root@ab26a4643071:/test# ./driverkit docker --output-module ./test-amazonlinux2.ko --timeout 520 --target amazonlinux2 --kernelrelease 5.4.186-102.354.amzn2.x86_64 --driverversion=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4 --kernelversion 1
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
```

**Additional Context**
Looking at previous MRs... It seems there was a recent change to set `CGO_ENABLED` to 0: https://github.com/falcosecurity/driverkit/pull/157/files

~~I wonder if setting `CGO_ENABLED=0` only for arm builds would solve the issue? Maybe make the Makefile detect if arm, then `CGO_ENABLED=0`?~~
I tried adding some logic to the Makefile to detect arm vs. x86, and it *does* get x86 building again... But the `mattn/go-sqlite3` lib requires `CGO_ENABLED=1` to run.

### PR DESCRIPTION
**Pull request by EXONER4TED**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area cmd

> /area pkg

> /area docs

> /area tests

**What this PR does / why we need it**:

On the latest release, 0.9.0, Amazon Linux 2 kernel drivers fail to build due to `CGO_ENABLED=0` for the go compilation. Amazon Linux 2 appears to store its kernel information in sqlite, and the lib driverkit uses today requires `CGO_ENABLED=1` to work (`mattn/go-sqlite3`). 

@dwindsor sent me a doc describing an alternative to `mattn/go-sqlite3` that does not require CGO whatsoever: https://datastation.multiprocess.io/blog/2022-05-12-sqlite-in-go-with-and-without-cgo.html

I've swapped out the lib for `modernc.org/sqlite` and updated the driver import - now builds are working again on x86:
```
root@c36786393cb7:/test# ./_output/bin/driverkit docker --output-module ./test-amazonlinux2.ko --timeout 520 --target amazonlinux2 --kernelrelease 5.4.186-102.354.amzn2.x86_64 --driverversion=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4 --kernelversion 1 
INFO driver building, it will take a few seconds   processor=docker
INFO kernel module available                       path=./test-amazonlinux2.ko
```

**Which issue(s) this PR fixes**:

Fixes #158

**Special notes for your reviewer**:

Interestingly, building/running with this new sqlite lib on an M1-based Mac (arm), I get a new error:
```
error="kernel not found"
```
I'm not sure if that's expected trying to run the same build command (building an x86_64 amazonlinux2 driver) on arm or if more work needs to be done to make this work...

```release-note
NONE
```

### CODE REVIEW

**Review by leodido — DISMISSED** [review]
This LGTM

I'd like to merge it ASAP (and release 0.9.1) because at the moment release 0.9.0 is not fully functional. Thank you for sending this patch!

Can you please sign-off your commit? 🙇

**Comment by dwindsor** [comment]
@EXONER4TED git commit --amend --signoff, then force push

**Comment by EXONER4TED** [comment]
Apologies, think I borked the bot because I didn't have my GPG key setup to verify my commits originally... I rewrote the commit history to verify the commits. 

image

Unsure of how to get it to sign off at this point... Do I just try:

/dco-signoff: yes

**Comment by EXONER4TED** [comment]
There we go, thanks @dwindsor - unsure what I did wrong the first time

**Comment by FedeDP** [comment]
@leodido @dwindsor i am really sorry for the issue; had a brief talk with @leogr and we didn't think about sqlite; we though that was a leftover from a copy paste from another project and then i proceeded. (note the original line was from Leo).
Thanks @EXONER4TED for the fix, and again sorry for the inconvenience.
I am planning to add some integration tests to avoid future breaks.

Btw, are [SQLITE_TAGS](https://github.com/falcosecurity/driverkit/blob/master/Makefile#L34) in makefile still needed?

**Pull request merged**
