### PR TITLE
cleanup(pkg): store kernelversion inside the kernelrelease type.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area pkg

**What this PR does / why we need it**:

Since it is only used by ubuntu, avoid directly calling `viper.GetString()`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dwindsor** [comment]
/approve

cc @EXONER4TED, this may affect his use case.

**Review by EXONER4TED — APPROVED** [review]
looks good to me 🙂

**Pull request merged**
