### PR TITLE
new(builder): add bottlerocket os support.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area pkg

**What this PR does / why we need it**:

Adds support for bottlerocket, using same mechanism as minikube; see kernel-crawler PR: https://github.com/falcosecurity/kernel-crawler/pull/79

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new: add support for bottlerocket
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Wait on https://github.com/falcosecurity/kernel-crawler/pull/79 to be merged first.

**Comment by dwindsor** [comment]
Still not quite sure how this works given Bottlerocket's read-only rootfs, but this is great! 🚀

**Review by dwindsor — COMMENTED** [review]
Still not quite sure how this works given Bottlerocket's read-only rootfs, but this is great! 😆🚀

**Comment by FedeDP** [comment]
It does indeed allow to build kmod/ebpf probe; see: https://github.com/bottlerocket-os/bottlerocket/issues/2275#issuecomment-1186315503

**Comment by FedeDP** [comment]
kernel-crawler PR was merged ;)

**Comment by FedeDP** [comment]
We now have bottlerocket entries in kernel-crawler generated json: https://falcosecurity.github.io/kernel-crawler/?arch=x86_64&target=BottleRocket.
I think we can merge this ;)

**Comment by dwindsor** [comment]
This is excellent! Maybe we can use the same approach for CoreOS...

**Review by dwindsor — APPROVED** [review]

**Pull request merged**
