### PR TITLE
fix(docker): Use debian 10 buster as builder base

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area cmd

> /area pkg

> /area docs

> /area tests

**What this PR does / why we need it**:

`debian:stable` recently became debian 11, which is not compatible with some packages that we install in the image, that assumes that `debian:stable` is debian 10 `buster`. While this doesn't fix all issues in that department it will allow the builder to work on the set of config files that worked until now.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(docker): fix debian version in the builder image
```

### CODE REVIEW

**Comment by dwindsor** [comment]
+1 for getting this merged in

**Comment by Issif** [comment]
@leogr @leodido @fntlnz Can we merge this PR thanks? I will allow us to be focus next on #111 which embeds same fix and more fix for important blockers for the community.

**Comment by fntlnz** [comment]
#111 introduces the same change. We can close this one

**Comment by LucaGuerra** [comment]
Superseded by https://github.com/falcosecurity/driverkit/pull/111

**Pull request closed without merging**
