### PR TITLE
fix(build): fix arm64 support on alpine (that is used by official docker image)

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area cmd

> /area pkg

> /area docs

> /area tests

**What this PR does / why we need it**:

Basically, we've been hit by the same bug as https://github.com/falcosecurity/event-generator/pull/66.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by dwindsor — APPROVED** [review]

**Review by dwindsor — APPROVED** [review]

**Comment by FedeDP** [comment]
Closing and reopening to trigger poiana :D 
/close

**Comment by leogr** [comment]
I've fixed @poiana :) 
Closing and reopening to ping our beloved bot :heart_decoration: 

/close

**Pull request merged**
