### PR TITLE
cleanup(OWNERS): remove inactive approvers

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

/kind documentation

**Any specific area of the project related to this PR?**

/area docs

**What this PR does / why we need it:**

For https://github.com/falcosecurity/falco/issues/2115, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from approvers to emeritus_approvers in OWNERS.

**Which issue(s) this PR fixes:**

**Special notes for your reviewer:**

### CODE REVIEW

**Review by fntlnz — CHANGES_REQUESTED** [review]
Please restore `fntlnz` https://github.com/falcosecurity/falco/issues/2115#issuecomment-1176045086

**Review by dwindsor — APPROVED** [review]

**Comment by dwindsor** [comment]
Closing in favor of #181

**Comment by jasondellaluce** [comment]
@dwindsor, for better traceability, this is superseded by #182 and not #181.

@fntlnz, given https://github.com/falcosecurity/falco/issues/2122 I understand that you'd like to step down as maintainer of this repository too, so can you please remove your Change Request to unblock @dwindsor's approval? Alternatively, can you sign-off your commit on #182 to unblock the DCO there?

**Pull request closed without merging**
