### PR TITLE
new(pkg/driverbuilder): support photonOS 5.0.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area pkg

**What this PR does / why we need it**:

Moreover, support aarch64 kernelurls for it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(pkg/driverbuilder): support photonOS 5.0.
```

### CODE REVIEW

**Review by dwindsor — DISMISSED** [review]

**Comment by FedeDP** [comment]
I had to revert fb7fb6445afac8cb8e863d1783430ed1a02b8f01 since debian friends fixed it after all :D

**Review by dwindsor — APPROVED** [review]

**Pull request merged**
