### PR TITLE
Fix CI failure

### PR DESCRIPTION
**Pull request by dwindsor**
Signed-off-by: David Windsor <dwindsor@secureworks.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area cmd

> /area pkg

> /area docs

> /area tests

**What this PR does / why we need it**:

#171 got approved lightning quick (before CI had finished), and integration_tests is failing. This fixes it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by dwindsor** [comment]
@leodido

**Comment by FedeDP** [comment]
`gcc-10` is not available on our builder image: https://github.com/falcosecurity/driverkit#3-customize-gcc-version; neither it can be easily added because of glibc version.
This is something we should address using multiple builder images IMO.
See master failing integration tests (https://app.circleci.com/pipelines/github/falcosecurity/driverkit/304/workflows/503f6b45-2597-41d3-ac7d-107651cba53b/jobs/455/parallel-runs/0/steps/0-106)
```
ln -sf /usr/bin/gcc-10 /usr/bin/gcc 
cd /tmp/driver  
...
make[1]: gcc: Command not found
```

**Comment by FedeDP** [comment]
I see, the GCCVersion is useful when using another builder image!
That makes sense! It would break without using a new builder image but driverkit would fail to build the driver in any case using the old GCC8.
:+1: from me!

**Comment by dwindsor** [comment]
> I see, the GCCVersion is useful when using another builder image! That makes sense! It would break without using a new builder image but driverkit would fail to build the driver in any case using the old GCC8. 👍 from me!

I agree this is a hacky temporary fix, though. This problem should be addressed in the [base builder](https://github.com/falcosecurity/driverkit/blob/master/build/builder.Dockerfile), but adding gcc-10 there would require us to address underlying glibc/binutils compatibility issues - a significant change that deserves its own PR.

**Review by leodido — APPROVED** [review]

**Pull request merged**
