### PR TITLE
Draft: Adjust the `kernelVersionPattern` to match some weird Debian kernels

### PR DESCRIPTION
**Pull request by EXONER4TED**
Signed-off-by: Logan Bond <lbond@secureworks.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area cmd

/area pkg

> /area docs

> /area tests

**What this PR does / why we need it**:
I found some strange Debian kernels with kernel crawler in my testing... However, driverkit fails to build all of them:
```
    - '4.9.65-2+grsecunoff1~bpo9+1-amd6'
    - '4.19.118-2+deb10u1~bpo9+1-amd64'
    - '5.10.127-2~bpo10+1-amd64'
    - '5.19.11-1~bpo11+1-amd64'
    - '5.10.136-1~deb10u3-amd64'
    - '4.9.189-3+deb9u2~deb8u1-amd64'
    - '4.19.232-1~deb9u1-amd64' 
```
Tracing it back through the code... it seems the `kernelVersionPattern` regex needs to be adjusted for these special characters. Otherwise, the pattern doesn't match correctly and driverkit immediately bails out and errors that the CLI options don't pass validation.

**Which issue(s) this PR fixes**:

Fixes # N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by EXONER4TED** [comment]
Thank God for regex101.com lol
image

**Comment by EXONER4TED** [comment]
Updated match after adding another `+` later in the pattern:
image

**Comment by dwindsor** [comment]
Nice! Thanks for this PR!

Could we add test cases to kernelrelease_test.go for the new debian formats that are now matchable by this regex, so we can be sure future updates don't break it:
Screen Shot 2022-10-25 at 3 32 33 PM

**Comment by EXONER4TED** [comment]
Adding tests actually caught an issue, so great call out @dwindsor 🙂 I wasn't properly grabbing the extra version. Updated capture shot:
image

**Comment by FedeDP** [comment]
Wow now the regex is much more readable :joy:
Thanks for this!
Given the tests, it LGTM!

**Review by dwindsor — APPROVED** [review]

**Pull request merged**
