### PR TITLE
new: builder images tags via OCI

### LINKED ISSUE #256: Usage and break of builder image listing
**Motivation**
The new feature of auto listing of builder image totally break the usage of Driverkit inside a deployed Kubernetes Pod.

The function ImageSearch seems to look for the local unix socket, but, as the DinD is an unsafe pratice, this kind of right (accessing Docker socket, so Privileged pods) is not an option I want to deploy. 
Resulting ImageSearch to fail, causing the build to fail. 

Another problem with the current implementation is the authentication to private repositories that seems not handle. And it seems that the command `docker search` struggle to work with gitlab container registry,

In another topic, I find putting gcc version inside the builder image name not quite optimum. A solution could be to apply multiple tag to images containing multiple gcc version, i.e.:
`driverkit-builder-any-x86_64:gcc-8.0.0`, `driverkit-builder-any-x86_64:gcc-6.0.0`, `driverkit-builder-any-x86_64:gcc-5.0.0`, ... could point the same image containing the multiple gcc versions avoiding to create ultra long name, creating a better flavoring.

**Feature**

- Fix the usage of Docker SDK Client to be able to search without the Docker unix socket + token/auth management for custom repos 
- Possible rename/rework of builder images organization

**Alternatives**

I tried to deep dive the docker SDK, but I can't find a way to fix it.
The usage of Docker search API function add a big complexity while a simple check of present of base image name, with a possible prefix, and with flavoured tag for gcc and with a possible flavoured tagname for target-specific build (other images than `any`ones) could erase most of that complexity.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area cmd
/area pkg
/area docs

**What this PR does / why we need it**:

Multiple things are fixed:
* no more `docker search`; instead we will use falcoctl OCI utilities to retrieve list of tags for a docker repository
* moved our builder image name protocol to properly use a docker repo + tag (see below notes for reviewers)
* added back a default builder image tag, so that eg: driverkit releases will, by default, use builder images tagged together with them. This was a behavior once upon a time that was completely dropped some months ago. 
I think it still makes sense therefore i added it back.
* For `FileImageLister` make explicit the `arch` and `tag` shipped by an image entry
* Improved docs

**Which issue(s) this PR fixes**:

Fixes #256 

**Special notes for your reviewer**:

CI will fail because we changed the builder image names protocol.
Old protocol:
* `falcosecurity/driverkit-builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0:latest`

New protocol:
* `falcosecurity/driverkit-builder:any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0-latest`

As you can see, we now properly have a docker repository; to still be able to retrieve desired image tag (ie: latest) we had to add the `-latest` suffix.

As always, we might want to:
* either push the new builder images to a different repo (eg: `fededp/driverkit-builder`)
* or disable integration tests, merge this, and enable them back; this way master CI will take care of pushing new builder images for us

I'd go with the first (as it was the case other times we broke the builder images names), but i am currently using my smartphone internet data, therefore am not able to do so :) 

**Does this PR introduce a user-facing change?**:

```release-note
new: fetch list of builder images via falcoctl OCI utilities
```

### CODE REVIEW

**Comment by EXONER4TED** [comment]
The changes look good, I'm fine to just disable tests for this PR to let it build the new images for us.

**Comment by EXONER4TED** [comment]
I'm not familiar with CircleCI... how do we disable those temporarily? Can you just comment them out in code? I suspect the project rules will require it though.

**Comment by FedeDP** [comment]
We can just skip the `make integration_test` step: https://github.com/falcosecurity/driverkit/blob/master/.circleci/config.yml#LL19C7-L19C7

**Comment by FedeDP** [comment]
I think we can wait a little bit more and then eventually consider any non-answer as yes :) 
Thank you!

**Comment by FedeDP** [comment]
Dropped integration tests! :pray: for CI

**Comment by FedeDP** [comment]
Imho we can go now @EXONER4TED ! :) Thank you!

**Comment by FedeDP** [comment]
I added some more tests around `FileImagesLister` in latest commit!

**Review by EXONER4TED — APPROVED** [review]
🙏

**Pull request merged**
