### PR TITLE
feat(debian-pve-build): compile proxmox kernel's driver

### PR DESCRIPTION
**Pull request by Lowaiz**
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area pkg

**What this PR does / why we need it**:

Proxmox kernel are based on Debian, but has customs headers name. This litlle change make possible the compilation of the driver of a proxmox kernel.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
"NONE" 
```

### CODE REVIEW

**Review by FedeDP — COMMENTED** [review]
Changes LGTM!
@falcosecurity/driverkit-maintainers wdyt?

**Comment by FedeDP** [comment]
Thanks @Lowaiz for this fix :)

**Comment by dwindsor** [comment]
Changes also look good to me!

**Review by dwindsor — APPROVED** [review]

**Comment by FedeDP** [comment]
Uh, i see, the required status check is wrong on test-infra :laughing:

**Pull request merged**
