### PR TITLE
vote: Applying for Maintainer

### PR DESCRIPTION
**Pull request by Lowaiz**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area docs

**What this PR does / why we need it**:

As proposed in #256, I'm quite exited to propose myself as `Driverkit` Maintainers, mainly to continue to support and improve the Kubernetes part in addition of improving automated usability, reviews MR and more if needed.

Whatever the result is, I really appreciate the proposal, it's always a pleasure to get our work recognize!

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you for this! You are very active and have great proficiency on a large chunk of driverkit.
For me, welcome aboard! :D 
:+1:

**Comment by leogr** [comment]
+1 NB

**Comment by EXONER4TED** [comment]
+1 from me 🙂

**Comment by dwindsor** [comment]
+1

**Comment by FedeDP** [comment]
So, we reached majority!
@Lowaiz welcome!
Please, make sure to add yourself in the test-infra repo. You need to add your gh handle to config/org.yaml under:
* members
* driverkit-maintainers

sections. See for example https://github.com/falcosecurity/test-infra/commit/56a5878f1439ee531c06d8c77e4f9ace2b595e27 :)

**Comment by Lowaiz** [comment]
Hey everyone,

Thank you for all these votes and the acceptation.

I'm going the PRs for evolution and test-infra repo right now.

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
@Lowaiz feel free to re-trigger verify-owners once you accept the invite to the falcosecurity org :)

**Comment by Lowaiz** [comment]
@FedeDP It seems ok !

**Comment by FedeDP** [comment]
Yay! @Lowaiz you can now open the second PR on test-infra ;)

**Pull request merged**
